// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{type: 'autogenerated', dirName: '01-cours'}],
  tp: [{type: 'autogenerated', dirName: '02-tp'}],
  pyrefs: [{type: 'autogenerated', dirName: '03-Références Python'}],
  exerc: [{type: 'autogenerated', dirName: '04-exercices'}],
};

module.exports = sidebars;
